ci: enable cruft workflow pr creation
MartinBernstorff/swift-python-cookiecutter pull request #18
Opened 2023-03-16 18:13 UTC by MartinBernstorff

Example is available here: https://github.com/MartinBernstorff/test-create-pr-if-cruft-fails/pull/8

2023-03-16 21:22 UTC, KennethEnevoldsen requested changes
Really only want the token added to a setup file (the one in the other PR.

2023-03-16 21:22 UTC, KennethEnevoldsen commented on {{cookiecutter.project_name}}/.github/workflows/cruft.yml
> +        # This steps requires a personal access token with write permissions to the repository.
Add to the setup file

2023-03-16 21:22 UTC, KennethEnevoldsen commented on {{cookiecutter.project_name}}/.github/workflows/cruft.yml
>          uses: actions/checkout@v2
Would update to v3 since we are doing the update

2023-03-16 21:22 UTC, KennethEnevoldsen commented on {{cookiecutter.project_name}}/.github/workflows/cruft.yml
>          uses: actions/setup-python@v2
would update to v4

2023-03-17 07:48 UTC, MartinBernstorff commented
Thanks a ton! Updated - waiting for PAT conversation in #20.

2023-03-17 09:20 UTC, KennethEnevoldsen approved these changes

2023-03-17 09:21 UTC, merged